spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect